### ISSUE TITLE
Multiple concurrent trades

### ISSUE THREAD

**Issue by scionaltera** [agonyforge/arbitrader#13]
The bot should be able to support multiple concurrent trades.

Be sure to take the amount of margin into account for each exchange to avoid over-leveraging. For simplicity, maybe limit to one trade per exchange for now.

**Comment by scionaltera** [comment]
Getting closer to being able to do this. I have pulled all the state for the active trades into its own `ActivePosition` model object. I think the next step would be to pull that object out into its own service that can manage more than one of them at a time.

The biggest difficulty that I personally have is that because of restrictive US laws I'm down to just one exchange that can support margin trading. So if I open one set of trades with 90% of my balance on Kraken, I cannot open a short position anywhere else... maybe once #66 is done I could set it to like 45% and add a configuration option for a maximum of 2 concurrent positions? 🤔

**Comment by sanitariu** [comment]
If liquid is still working i will test this with real money.

**Comment by scionaltera** [comment]
@dazito and I are making some progress on an architecture design that will allow this.
