### ISSUE TITLE
Fee calculation before trading

### ISSUE THREAD

**Issue by AllirionX** [agonyforge/arbitrader#316]
The fees are not taken into consideration before deciding to enter or exit a trade, which can lead to negative trades.

The current positive spread calculation is (pseudo code below): 
```
long entrySpread = shortPrice/longPrice - 1;
long exitSpread = 1 - shortPrice/longPrice;
```

The spread is the percentage difference between the long and short price. 
To take the fees into account we need to replace the shortPrice and longPrice with the effective shortPrice and longPrice with the equivalent price including the fees. The fees will decrease the price of sell orders and increase the price of buy orders.

```
//BUY
long entryEffectiveLongPrice = longPrice * (1+longFee);
long exitEffectiveShortPrice = shortPrice * (1+shortFee);

//SELL
long entryEffectiveShortPrice = shortPrice * (1-shortFee) ;
long exitEffectiveLongPrice = longPrice * (1-longFee);
```

The effective spreads are:
```
long effectiveEntrySpread = shortPrice * (1 - shortFee) / (longPrice * (1 + longFee)) -1;
long effectiveExitSpread = 1 - shortPrice * (1 + shortFee) / (longPrive * (1 - longFee));
```

As expected,  with 0 fees the formulas are the same and increasing the fees decrease the spread (making it harder to enter or exit trades). 

Example for a trade entry:
```
longPrice = 1000
shortprice = 1010
shortFee = 0.0026
longFee = 0.005
effectiveShortPrice = 1010 * (1 - 0.0026) = 1007.374
effectiveLongPrice = 1000 * (1 + 0.005) = 1005

spread = 1010/1000 -1 = 0.0100
effectiveSpread = 1007.374 / 1005 -1 = 0.0022
```

The spread limits would need to be lowered as they don't need to compensate for the fees anymore.

**Comment by scionaltera** [comment]
Ok this makes sense to me. I can put a branch together and see how it goes.

**Comment by AllirionX** [comment]
The fix should make sure to take the decision to trade based on the final effective price. The 'effective price' is the price you pay for 1COIN, after fee, step size rounding, scale rounding etc
