### ISSUE TITLE
True market neutrality

### ISSUE THREAD

**Issue by AllirionX** [agonyforge/arbitrader#325]
The current trading strategy is not truly market neutral as the profit depends on the exit price, the higher the exit price the more profitable the trade. 
If the exit price converge, a true market neutral strategy would:
- only depend on the entry prices and spread
- take the fees into account

This is pretty hard to grok assertion, so I will do my best to demonstrate:
1. Why is the current strategy not market neutral
2. What would a true market neutral strategy be
3. How to include the exchange fees and keep a market neutral strategies

### Part I - Why the current strategy is not market neutral
In this ticket the profit of a trade is the sum of the 4 trades.
```
profit = volumeShort*entryPriceShort  - volumeLong*entryPriceLong 
         - volumeShort*exitPriceShort + volumeLong*exitPriceLong
```
The current trading strategy calculate the volumes traded on both long and short exchanges by
`volume = exposure/entryPrice` so we spend as much on the short entry as on the long entry

Because of that the profit becomes:
```
profit = - volumeShort*exitPriceShort + volumeLong*exitPriceLong
```

When the price converge to an exitPrice:
```
profit = (volumeLong - volumeShort) * exitPrice
```

Because we volume on the Long exchange is bigger than the volume on the short exchange, if the exit price increases, the profit increases. If the exit price decreases, the profit decreases.

**Example:** in the README example, if instead of going up to $1550, the BTC price went down to 0, we would have exited the trade with 0 profit. 
**This is not truly market neutral.**

### Part II - A true neutral strategy
Instead of calculating a different volume to trade for the short and long exchanges, we can trade same volume on both.
```
profit = volume*entryPriceShort  - volume*entryPriceLong 
         - volume*exitPriceShort + volume*exitPriceLong
```

When the price converge to an exitPrice:
```
profit = volume*entryPriceShort  - volume*entryPriceLong
profit = volume*(entryPriceShort - entryPriceLong)
```
The profit here only depends on the volume traded (that we control) and the entry price difference. **This is market neutral**

**Example:** in the README example, instead of entering the trade buy shorting 0.95BTC and going long on 1.05BTC, we trade 1BTC on both exchange.

After entry trade of 1BTC
```
Exchange Balances
Short $2050 (sold 1BTC for 1050$)
Long $50 (bought 1BTC for 50$)
```
Now the price converge to $1550 and we exit the trade
After entry trade of 1BTC at $1550
```
Exchange Balances
Short $500 (bought 1BTC for 1550$)
Long $1600 (sold 1BTC for 1550$)
Total $2100
```

If instead the price converges to $0, we exit the trade
After entry trade of 1BTC at $0
```
Exchange Balances
Short $2050 (bought 1BTC for 0$)
Long $50 (sold 1BTC for 0$)
Total $2100
```

In both scenarios the the profit in $100, which is the difference between the long and short entry price times the traded volume (1BTC).

### Part III - Where we add fees
Fees are in percentage so they depends on the entry and exit prices. They increase if the price increase. The entry fees are not a problem as they are known before trading. The exit fees however, make the trade less profitable if the price increase.
Thankfully this is the opposite behavior from the existing strategy in Part I, and just like in Part I we can buy just a bit more on the long exchanges to compensate the fees.

We can use
`volumeLong = V * (1 + shortFee) / (1 - longFee) `where V is volumeShort, and where shortFee and longFee are fee percentages

This extra volume traded on the long exchange will compensate for the exit fees.

Demonstration is indigest but here we go:
```
profit = V*entryPriceShort*(1-shortFee)  - volumeLong*entryPriceLong*(1+longFee) // does not depend on the exit price
    - V*exitPriceShort*(1+shortFee) + volumeLong*exitPriceLong*(1-longFee) //should be equal to 0
```

We are only interested in making sure that the part depending on the exitPrice is equal to 0, and we replace volumeLong by its new expression:
   - V * exitPrice *(1 + shortFee) + volumeLong * exitPrice * (1 - longFee) 
= - V * exitPrice * (1 + shortFee) + V * (1 + shortFee) / (1 - longFee)*exitPrice*(1 - longFee)
= V * exitPrice * (-1 - shortFee + (1 + shortFee) / (1 - longFee) * (1 - longFee)) 
= V * exitPrice * ( -1 - shortFee +1 + shortFee) 
= V * exitPrice * 0 `

When the price converge to an exitPrice:
```
profit = volume*entryPriceShort  - volume*entryPriceLong
profit = volume*(entryPriceShort - entryPriceLong)
```
The profit here only depends on the volume traded (that we control) and the entry price difference. **This is market neutral**

**Example:** in the README example, instead of entering the trade buy shorting 0.95BTC and going long on 1.05BTC, we trade 1BTC on both exchange.

After entry trade of 1BTC
```
Exchange Balances
Short $2050 (sold 1BTC for 1050$)
Long $50 (bought 1BTC for 50$)

```
Now the price converge to $1550 and we exit the trade
After entry trade of 1BTC at $1550
```
Exchange Balances
Short $500 (bought 1BTC for 1550$)
Long $1600 (sold 1BTC for 1550$)
Total $2100
```

If instead the price converges to $0, we exit the trade
After entry trade of 1BTC at $0
```
Exchange Balances
Short $2050 (bought 1BTC for 0$)
Long $50 (sold 1BTC for 0$)
Total $2100
```

In both scenarios the profit is $100, which is the difference between the long and short entry prices, times the traded volume (1BTC).

### Part III - Where we add fees
Fees are in percentage so they depends on the entry and exit prices. They increase if the price increase. The entry fees are not a problem as they are known before trading. The exit fees however, make the trade less profitable if the price increase.
Thankfully this is the opposite behavior from the existing strategy in Part I, and just like in Part I we can buy just a bit more on the long exchange to compensate for the fees.

We can use
```
volumeLong = V * (1 + shortFee) / (1 - longFee) 
```
where `V` is volumeShort, and where `shortFee` and `longFee` are fee percentages

This extra volume traded on the long exchange will compensate for the exit fees.

Demonstration is indigest but here we go:
```
profit = V*entryPriceShort*(1-shortFee)  - volumeLong*entryPriceLong*(1+longFee) // does not depend on the exit price
               - V*exitPriceShort*(1+shortFee) + volumeLong*exitPriceLong*(1-longFee) // should be equal to 0
```

We are only interested in making sure that the part depending on the exitPrice is equal to 0, and we replace volumeLong by its new expression:
```
-V * exitPrice *(1 + shortFee) + volumeLong * exitPrice * (1 - longFee) 
= -V * exitPrice * (1 + shortFee) + V * (1 + shortFee) / (1 - longFee)*exitPrice*(1 - longFee)
= V * exitPrice * (-1 - shortFee + (1 + shortFee) / (1 - longFee) * (1 - longFee)) 
= V * exitPrice * ( -1 - shortFee +1 + shortFee) 
= V * exitPrice * 0 
= 0
```

Now the profit when the price converge is only
```
profit = V*entryPriceShort*(1-shortFee)  - volumeLong*entryPriceLong*(1+longFee)
```
where `V= volumeShort` and `volumeLong = V * (1 + shortFee) / (1 - longFee)`
**This is market neutral, even after fees,** as the profit does not depend on the exit, it only depends on the entry price and the fees percentage we know of before trading.

A spreadsheet is shared via discord with a comparison of the existing and proposed strategy to calculate the trade volumes.

**Comment by AllirionX** [comment]
The strategy in part III express the relationship between the volumeShort, volumeLong. It does not show how to find the initial volumeShort or volumeLong.

`longVolume = shortVolume * feeFactor` where `feeFactor = (1 + shortFee) / (1 - longFee)`


```
//Calculate the fee factor and the max exposure on the short and long exchange
feeFactor = (1 + shortFee) / (1 - longFee);
longExposure = longBalance * 0.9;
shortExposure = shortBalance * 0.9;

//Find longVolume1 such as:  longVolume1 * longPrice <= longExposure
longVolume1 = longExposure / longPrice;

//Find longVolume2 such as shortVolume * shortPrice <= short Exposure
//This is equivalent to longVolume2 / feeFactor * short Price <= shortExposure
longVolume2 = feeFactor * shortExposure / shortPrice;


longVolume = min(longVolume1, longVolume2);
shortVolume = longVolume / feeFactor;
```

**Comment by AllirionX** [comment]
The strategy in part III, is based on a converging exitPrice common to both exchanges. This is the same as having an exitTarget of 0.

With an `exitTarget = exitPriceShort/ exitPriceLong -1`

the volumeLong needs to be calculated as:

`volumeLong = volumeShort * (1 + exitTarget) *  (1 + shortFee) / (1 - longFee)`

**Comment by dazito** [comment]
Having exitTarget set as 0 (zero), then maybe we can simplify and remove it from the configuration file? Or you think it is still a good idea to have an exitTarget from the assumption that prices may take a lot of time to actually converge to a zero (or near zero) difference?

**Comment by AllirionX** [comment]
I think the exitTarget is still useful to decide when to exit a trade. 
The problem was that the maths in the ticket use the assumption that prices converge:
`exitPriceShort = exitPricelong` (ie. exitTarget == 0), but in reality it is `exitPriceShort = exitPriceLong * (1 + exitTarget)` and the exitTarget is rarely 0, so the maths (and the implementation) needs to be adapted.

Maybe exitTarget could be removed from the configuration as part of https://github.com/agonyforge/arbitrader/issues/316 or https://github.com/agonyforge/arbitrader/issues/329
