### ISSUE TITLE
Error when running docker-compose up

### ISSUE THREAD

**Issue by dchakarov** [agonyforge/arbitrader#334]
Hi, I tried following the wiki and when I try docker-compose up, I get this error:

```
# docker-compose up
Pulling arbitrader (agonyforge/arbitrader:latest)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling arbitrader (agonyforge/arbitrader:latest)...
ERROR: pull access denied for agonyforge/arbitrader, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

I googled but couldn't find any solutions. I am logged in to Docker. I tried both on macOS and Ubuntu.

**Comment by scionaltera** [comment]
I am certain this has to do with moving the project from my personal account into our new organization last week. Try using scionaltera/arbitrader:latest in your Dockerfile for now (we’re still publishing that image) and I’ll see about getting the new Docker Hub account up and running this week. Sorry for the confusion.

**Comment by dchakarov** [comment]
The workaround worked, thank you :)

**Comment by scionaltera** [comment]
I have created the agonyforge organization over at Docker Hub and pushed the latest image over to it. It is possible to pull `agonyforge/arbitrader` now.

**Comment by dchakarov** [comment]
If I try now I get this error:

> ERROR: manifest for agonyforge/arbitrader:latest not found: manifest unknown: manifest unknown

Do I need to wait for the PR to get merged?

**Comment by scionaltera** [comment]
> Do I need to wait for the PR to get merged?

Sorry, yes. The `latest` tag will get pushed with the build when the PR is merged. I pushed a `pr-337` tag as a test.
