### ISSUE TITLE
No trade combinations listed

### ISSUE THREAD

**Issue by mavirroco** [agonyforge/arbitrader#368]
this means there is an error on application.yaml?

**Comment by scionaltera** [comment]
That message isn't an error. It just means we haven't defined any Spring profiles and Spring is telling us it's going to use the default profile. We don't define any Spring beans that use profiles, so there is no effect from using the default profile. Nothing to worry about. :)

**Comment by mavirroco** [comment]
ok thanks for reply ..well i just wonder why not work cause i put run this for a while and no new messages
![image](https://user-images.githubusercontent.com/728028/111677387-8c914500-87f5-11eb-8940-aa93d238de85.png)

**Comment by mavirroco** [comment]
i have this in application.yaml  i changed to txt at the end for can upload here... 
my question is maybe i set wrong something?
[application.yaml.txt](https://github.com/agonyforge/arbitrader/files/6166531/application.yaml.txt)

**Comment by scionaltera** [comment]
Ok, the line after that "Trading the following exchanges and pairs:" should have a list of the pairs being traded. The fact that it's empty means the bot is not doing anything. For reference, mine looks like this:
<img width="1099" alt="Screen Shot 2021-03-18 at 11 36 19 AM" src="https://user-images.githubusercontent.com/1952888/111679161-3d8be580-87de-11eb-83b9-15d2b62b3b53.png">

There are a number of reasons something like that could happen, so let me briefly explain the process the bot goes through to create that list. Those are what we call "trade combinations". It's a pair of exchanges and a currency pair. For example, `Gemini/Kraken LTC/USD` means we're using Gemini to make the long trade, Kraken to make the short trade, and LTC/USD as the currency.

For a trade combination to work you must have three things:

* A "long" exchange where you can use a fiat currency (USD, EUR, etc.) to buy a cryptocurrency (BTC, ETH, LTC, etc.).
* A "short" exchange where you can use margin to borrow cryptocurrency to sell for fiat. In your configuration you would have a line that says `margin: true` for this exchange.
* Those two exchanges must both support at least one of the same currency pairs.

The bot goes through all the exchanges that you configured and automatically figures out these trade combinations for you. If it doesn't list any combinations it means that none of the exchanges in your configuration met the criteria I listed above.

Thanks for providing your configuration, and even more for _not_ including your API keys. :)

It looks like both the exchanges in your configuration have `margin: false` which is appropriate. I don't think either one of those exchanges supports margin trading. You'll need to add at least one more exchange that does support margin before the bot will create any trade combinations. If you're in the US I suggest Kraken<sup>1</sup> . If you're in the EU you can also try Liquid<sup>2</sup>.

Hopefully that helps get you started. Let me know if you have any other questions.

<sup>1</sup> I'm not affiliated with Kraken in any way but I am a customer. They are currently the only exchange that supports margin and is supported by XChange (the library we use to connect to exchanges) and that allows customers from the USA.
<sup>2</sup> I'm not affiliated with Liquid/Quoine in any way but I used to be a customer. They dropped all of their US based customers so I can't use them any more, but I liked their service and look forward to when they can operate in the US again.

**Comment by mavirroco** [comment]
thanks a lot for the reply ,,,ok so margin to true now ...but your think i need one more exchange so this work? so gemini and cexio none of this works? how i can have a list of they support margin in USA

**Comment by scionaltera** [comment]
At the moment the only margin exchange I know of for US customers is Kraken. Coinbase Pro has a new margin feature that is in beta but XChange doesn't support it yet, so we can't either.
